export type WhirlwindClasses =
  
  | "f-bold" | "f-semibold" | "f-bolder" | "f-lighter"
  | "flx" | "flxclmn" | "flxclmn-manual" | "r-flxclmn" | "r-flxclmn-manual" | "flxrw" | "flxrw-manual" | "r-flxrw" | "r-flxrw-manual" | "in-flx" | "in-flx-manual" | "init-flx" | "init-flx-manual" | "u-flx" | "u-flx-manual"
  | "iflx" | "iflxclmn" | "r-iflxclmn" | "iflxrw" | "r-iflxrw" | "in-iflx" | "init-iflx" | "u-iflx"
  | "flxw-nwp" | "flxw-nwp-manual"
  | "iflxw-nwp"
  | "ff-arial" | "ff-georgia" | "ff-system" | "ff-mono"
  | "f-capt" | "f-capt-sm" 
  | "fs-italic" | "fs-nor" | "fs-obli" | "in-fs" | "init-fs" | "u-fs"
  | "in-iis" | "init-iis" | "u-iis"
  | "in-iie" | "init-iie" | "u-iie"
  | "cg1c" | "cg1rc"
  | "col-red" | "col-subatomic" | "col-rebecca" | "col-touhou" | "col-whirlwind" | "col-nextgen"
  | "in-cs" | "init-cs" | "u-cs"
  | "in-ar" | "init-ar" | "u-ar"
  | "grd"
  | "igrd"
  | "p1" | "p2" | "p4" | "p8"
  | "p1r" | "p2r" | "p4r" | "p8r"
  | "p1c" | "p2c" | "p4c" | "p8c"
  | "p1rc" | "p2rc" | "p4rc" | "p8rc"
  | "m1"
  | "m1r"
  | "m-step" | "m-step-r"
  | "in-mblk" | "init-mblk" | "u-mblk"
  | "in-msk" | "init-msk" | "u-msk"
  | "blk"
  | "iblk"
  | "sr-at" | "sr-ce" | "sr-gp" | "sr-os" | "in-sr" | "init-sr" | "u-sr"
  | "in-sit" | "init-sit" | "u-sit"
  | "fd-at" | "fd-blk" | "fd-flbck" | "fd-opt" | "fd-sw" | "in-fd" | "init-fd" | "u-fd"
  | "fk-at" | "fk-no" | "fk-nor" | "in-fk" | "init-fk" | "u-fk"
  | "pb1" | "pb2" | "pb1r" | "pb2r"
  | "cntnt" | "cntntico" | "cntntico-manual"
  | "fvl-cl" | "fvl-cntxt" | "fvl-dl" | "fvl-hl" | "fvl-ncl" | "fvl-ncntxt" | "fvl-ndl" | "fvl-nhl" | "fvl-no" | "fvl-nor" | "in-fvl" | "init-fvl" | "u-fvl"
  | "in-tuo" | "init-tuo" | "u-tuo"
  | "in-ord" | "init-ord" | "u-ord"
  | "atf-eoc" | "atf-eoq"
  | "aic-inf" | "in-aic" | "init-aic" | "u-aic"
  | "biew1c" | "biew1rc"
  | "bisw1c" | "bisw1rc"
  | "flwrt"
  | "iflwrt"
  | "inle"
  | "style-link" | "style-link-inv"
  | "in-as" | "init-as" | "u-as"
  | "style-list"
  | "flxb-a" | "flxb-a-manual" | "flxb-cntnt" | "flxb-cntnt-manual"
  | "iflxb-a" | "iflxb-cntnt"
  | "h1-mi" | "h1-ma" | "h1-mir" | "h1-mar"
  | "po-fs" | "po-f" | "po-s"
  | "br12" | "br12r"
  | "bgc-yellow" | "bgc-red" | "bgc-green";

declare module "react" {
  interface HTMLAttributes<T> {
    className?: WhirlwindClasses | string;
  }
}
